language: c
compiler:
  - gcc
#  - clang
cache:
  directories:
  - $HOME/OpenBlasInstall
env:
  - TORCH_LUA_VERSION=LUAJIT21
#  - TORCH_LUA_VERSION=LUA51
#  - TORCH_LUA_VERSION=LUA52
sudo: false
addons:
  apt:
    packages:
    - cmake
    - gfortran
    - gcc-multilib
    - gfortran-multilib
    - liblapack-dev
    - build-essential
    - gcc
    - g++
    - curl
    - cmake
    - libreadline-dev
    - git-core
    - libqt4-core
    - libqt4-gui
    - libqt4-dev
    - libjpeg-dev
    - libpng-dev
    - ncurses-dev
    - imagemagick
    - libzmq3-dev
    - gfortran
    - unzip
    - gnuplot
    - gnuplot-x11
before_script:
  - export ROOT_TRAVIS_DIR=$(pwd)
  - export INSTALL_PREFIX=~/torch/install
  -  ls $HOME/OpenBlasInstall/lib || (cd /tmp/ && git clone https://github.com/xianyi/OpenBLAS.git -b master && cd OpenBLAS && (make NO_AFFINITY=1 -j$(getconf _NPROCESSORS_ONLN) 2>/dev/null >/dev/null) && make PREFIX=$HOME/OpenBlasInstall install)
  - git clone https://github.com/torch/distro.git ~/torch --recursive
  - cd ~/torch && git submodule update --init --recursive
  - mkdir build && cd build
  - export CMAKE_LIBRARY_PATH=$HOME/OpenBlasInstall/include:$HOME/OpenBlasInstall/lib:$CMAKE_LIBRARY_PATH
  - cmake .. -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE=Release -DWITH_${TORCH_LUA_VERSION}=ON
  - make && make install
  - cd $ROOT_TRAVIS_DIR
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH
script:
  - ${INSTALL_PREFIX}/bin/luarocks install luaffi
  - ${INSTALL_PREFIX}/bin/luarocks install luaposix 33.4.0
  - ${INSTALL_PREFIX}/bin/luarocks install moses
  - ${INSTALL_PREFIX}/bin/luarocks install logroll
  - ${INSTALL_PREFIX}/bin/luarocks install classic
  - ${INSTALL_PREFIX}/bin/luarocks install torchx
  - ${INSTALL_PREFIX}/bin/luarocks install dpnn
  - ${INSTALL_PREFIX}/bin/luarocks install tds
  - ${INSTALL_PREFIX}/bin/luarocks install nninit
  - ${INSTALL_PREFIX}/bin/luarocks install https://raw.githubusercontent.com/Kaixhin/rlenvs/master/rocks/rlenvs-scm-1.rockspec
  - export PATH=${INSTALL_PREFIX}/bin:$PATH
  - export TESTLUA=$(which luajit lua | head -n 1)
  - ${TESTLUA} test/testAll.lua
notifications:
  email:
    on_success: change
    on_failure: change
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/faf2d7f3cc77829f144c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
